# Generated by Django 5.0.2 on 2024-02-20 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 20, 6, 22, 3, 447675, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
