# Generated by Django 5.0.2 on 2024-02-20 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
